name: KairoOS Build System (Stable Edition)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Limpeza Extrema e Swap
        run: |
          sudo swapoff -a || true
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc "/usr/local/share/boost" /usr/lib/jvm /usr/local/stack /usr/local/share/powershell /usr/local/lib/node_modules
          docker image prune --all --force
          sudo rm -f /swapfile
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Instalando Ferramentas e Bibliotecas Legadas
        run: |
          sudo apt-get update
          # Adicionamos libncurses5 e libncurses5:i386 para o Clang antigo funcionar
          sudo apt-get install -y bc build-essential zip curl libstdc++6 git python3 python3-pip python-is-python3 repo libncurses5

      - name: Configurando o Git
        run: |
          git config --global user.email "luisfelipe@exemplo.com"
          git config --global user.name "Luis Felipe"

      - name: Inicializando Código (KairoOS Android 11)
        run: |
          mkdir build && cd build
          repo init -u https://android.googlesource.com/platform/manifest -b android-11.0.0_r1 --depth=1 --groups=all,-notdefault,-device,-mips,-x86
          repo sync -c -j4 --force-sync --no-clone-bundle --no-tags

      - name: Compilando o KairoOS (Limpeza de Dependências)
        run: |
          cd build
          rm -rf device/google/cuttlefish
          rm -rf device/generic/opengl-transport
          
          source build/envsetup.sh
          lunch aosp_arm64-eng
          
          # Agora com a libncurses5 instalada, o Clang deve rodar liso
          m -j2 systemimage

      - name: Salvando Resultado
        uses: actions/upload-artifact@v4
        with:
          name: KairoOS-Image
          path: build/out/target/product/*/system.img
